# Generated by Django 4.2.7 on 2024-03-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('google_token', models.CharField(blank=True, max_length=255, verbose_name='Google Token')),
                ('credentials', models.TextField(blank=True, null=True, verbose_name='Credentials')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hall name')),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, verbose_name='Google calendar ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_halls', to='calendar_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(blank=True, max_length=255, verbose_name='event ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('error', models.BooleanField(default=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_events', to='calendar_app.company')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_events', to='calendar_app.hall')),
            ],
        ),
    ]
