# Generated by Django 4.2.7 on 2024-03-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date_start', 'date_end'], name='calendar_ap_date_st_995fcc_idx'),
        ),
    ]
