# Generated by Django 4.2.7 on 2024-03-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='page_token',
        ),
        migrations.RemoveField(
            model_name='event',
            name='page_token',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='page_token',
        ),
    ]
