# Generated by Django 4.2.7 on 2024-03-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_event_calendar_ap_date_st_995fcc_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='calendar_ap_date_st_995fcc_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date_start', 'date_end', 'event_hall'], name='calendar_ap_date_st_c3e47e_idx'),
        ),
    ]
