# Generated by Django 4.2.7 on 2024-03-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_remove_event_calendar_ap_date_st_995fcc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemodel',
            name='page_token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Page Token'),
        ),
    ]
