# Generated by Django 4.2.7 on 2024-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_alter_event_date_end_alter_event_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='error',
            field=models.IntegerField(default=0),
        ),
    ]
