# Generated by Django 4.2.7 on 2024-03-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_googlemodel_page_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='etag',
            field=models.CharField(blank=True, max_length=255, verbose_name='etag'),
        ),
    ]
